spring.application.name=vetcare

spring.datasource.url=jdbc:postgresql://localhost:5432/vetcare_db
spring.datasource.username=postgres
spring.datasource.password=NuevaClave123!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080